"""Age range column added

Revision ID: 2f3aa4decc6b
Revises: a9321fb28187
Create Date: 2024-10-30 22:17:56.932581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3aa4decc6b'
down_revision: Union[str, None] = 'a9321fb28187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age_range', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age_range')
    # ### end Alembic commands ###
