"""Age range column added

Revision ID: 82f29f2bf99b
Revises: 2f3aa4decc6b
Create Date: 2024-10-30 22:41:25.588921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f29f2bf99b'
down_revision: Union[str, None] = '2f3aa4decc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age_range', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age_range')
    # ### end Alembic commands ###
