"""Column Added

Revision ID: 93d4b5779860
Revises: c42ffe8544ee
Create Date: 2024-11-26 13:26:20.732434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d4b5779860'
down_revision: Union[str, None] = 'c42ffe8544ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('user', 'zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
